from decimal import *
from datetime import *
from typing import *

from dataclasses import dataclass
from marshmallow import Schema, fields, post_load
from openfabric_pysdk.utility import SchemaUtil
from mock_openfabric import Resource


################################################################
# Input concept class - AUTOGENERATED
################################################################
@dataclass
class InputClass:
    """Input class for the application"""
    prompt: Resource = Resource()
    attachments: List[str] = None


################################################################
# InputSchema concept class - AUTOGENERATED
################################################################
class InputClassSchema(Schema):
    prompt = fields.String(allow_none=True)
    attachments = fields.List(fields.String(allow_none=True), allow_none=True)

    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(InputClass(), data)
