from dataclasses import dataclass
from marshmallow import Schema, fields, post_load
from typing import Any, Dict, Optional

from openfabric_pysdk.utility import SchemaUtil
from mock_openfabric import Resource


################################################################
# Output concept class - AUTOGENERATED
################################################################
@dataclass
class OutputClass:
    """Output class for the application"""
    message: Resource = Resource()


################################################################
# OutputSchema concept class - AUTOGENERATED
################################################################
class OutputClassSchema(Schema):
    message = fields.Str(allow_none=True)

    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(OutputClass(), data)
